title:            gvNIX
logo:             logo-negativo-300.png
disqus_shortname: gvNIX
mail-to:          mailto:gvnixscm@gmail.com
download:         http://sourceforge.net/projects/gvnix/files/gvNIX-1.4.1.RELEASE.zip/download
quickstart:       https://github.com/DISID/gvnix-samples/tree/master/quickstart-app
demo-geo:         http://geo-gvnix.rhcloud.com/login?lang=en

# Assign a default image for your site's header and footer
default_bg:       default_bg.png
search:           true
share:            true

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true

# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url: http://www.gvnix.org
#url: http://localhost:4000

# Context path in the remote website (usually /<project>), will be prepended to absolute URLs for static resources
#baseurl: /gvnix

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments :
  provider : disqus
  disqus :
    short_name : gvnix

# Owner/author information
owner:
  name:           gvNIX
  avatar:         profile-gvnix.jpg
  email:          gvnixscm@gmail.com

  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  #description:    Some Details about yourself

# Social networking links used in footer. Update and remove as you like.
  twitter: http://twitter.com/gvnix
  facebook:
  github: http://github.com/gvSIGAssociation/gvnix
  stackoverflow: http://stackoverflow.com/questions/tagged/gvnix
  linkedin: https://www.linkedin.com/groups/gvNIX-entorno-desarrollo-rápido-aplicaciones-3878961

  # For Google Authorship https://plus.google.com/authorship
  #  google_plus:    "http://plus.google.com/123123123123132123"

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid

#
# Jekyll Configuration
#
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    2
paginate_path: "blog/page:num"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class


include: [".htaccess, .adoc, .asciidoc"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

# Production config

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://www.gvnix.org

#JB Configuration
# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.3.0

#
#Multilanguage
#
permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
    values:
      lang: es
      layout:
  -
    scope:
      path: _posts/en
    values:
      lang: en

# Links to include in top navigation
# For external links add external: true
links:
  en:
    doc:
      title: Changelog
#      url: /en/documentation
#      external: false
    training:
      title: Events
#      url: /en/training
#      external: false
#    blog:
#      title: "Blog"
#      url:   "/en/blog"
#      external: false
  es:
    doc:
      title: Control de cambios
#      url: /es/documentation
#      external: false
    training:
      title: Eventos
#      url: /es/training
#    blog:
#      title: "Blog"
#      url:   "/es/blog"
#      external: false

linksextra:
  en:
    featured:
      title: Featured
#      url: /en/featured
#      external: false
    springroo:
      title: Spring Roo
      url:   http://projects.spring.io/spring-roo/
      tooltip: Spring Roo Framework website
#      external: true
    contact:
      title: "Contact"
#      url:   "/en/contact"
#      external: false
    disid:
      title: DISID Corporation
      url:   http://www.disid.com
      tooltip: Lead Project website
  es:
    featured:
      title: Destacados
#      url: /es/featured
#      external: false
    springroo:
      title: Spring Roo
      url:   http://projects.spring.io/spring-roo/
      tooltip: Sitio web framework Spring Roo
#      external: true
    contact:
      title: "Contacto"
#      url:   "/es/contact"
#      external: false
    disid:
      title: DISID Corporation
      url:   http://www.disid.com
      tooltip: Sitio web empresa líder del proyecto

t:
  en:
    description: Tool for rapid web application development
    headline: Higher productivity thanks to its components with high functional value for corporate applications
    created: "Published by"
    author: "DISID"
    status: "Share this Status"
    status-posted: "Status posted "
    share-quote: "Share this Quote"
    share-twitter: "Share on Twitter"
    share-facebook: "Share on Facebook"
    share-google: "Share on Google plus"
    related-category: "Other posts from this category"
    read-more: "Read more about"
    read: "Read more ..."
    newer: "Newer Posts"
    older: "Older Posts"
    tagged: "Tagged with"
    posts-tagged: "Posts tagged with"
    post-featured: "Featured"
    post-changelog: "Releases"
    post-training: "Training"
    callout-btn-demo: "Online demo"
    callout-btn-quickstart: "Quickstart"
    callout-btn-download: "Download now"
    latest-news: "Latest news"
    all-news: "All news"
    legal-notice: "Legal notice"
    license-notice: "gvNIX and all its components are released under the "
    license-version: "GNU General Public License (GPL), Version 3.0"
    license-link: "http://www.gnu.org/licenses/gpl-3.0.html"
    license-contents-notice: "documentation under "
    license-contents-version: "CC BY-SA 3.0"
    license-contents-link: "http://creativecommons.org/licenses/by-sa/3.0/"
    back-to-blog: "Back"
    doc-samples: Sample Projects
    doc-guides: Getting Started Guides
    doc-tutorials: Tutorials
    doc-reference: Reference
    doc: Documentation
    additional-doc: Additional Documentation
    source-code: Source code
    less-1: Less than 1 minute read
    1-minute: 1 minute read
    read: minutes read
    see-more: Read more...
    changelog: Changelog
    modified: last modified on

  es:
    description: Herramienta de desarrollo rápido de aplicaciones web
    headline: Mayor productividad gracias a sus componentes de alto valor funcional para aplicaciones corporativas
    created: "Publicado por"
    author: "DISID"
    status: "Comparte esta entrada"
    status-posted: "Entrada publicada en "
    share-quote: "Comparte esta cita"
    share-twitter: "Compartir en Twitter"
    related-category: "Otras entradas de esta categoría"
    read-more: "Leer más sobre"
    read: "Leer más ..."
    newer: "Entradas más recientes"
    older: "Entradas más antiguas"
    tagged: "Etiquetado como"
    posts-tagged: "Entradas etiquetadas con"
    post-featured: "Destacado"
    post-changelog: "Versiones"
    post-training: "Formación"
    callout-btn-demo: "Demo online"
    callout-btn-quickstart: "Empieza ahora"
    callout-btn-download: "Descargar"
    latest-news: "Últimas noticias"
    all-news: "Todas las noticias"
    legal-notice: "Aviso legal"
    license-notice: "gvNIX y todos sus componentes están liberados bajo la "
    license-version: "Licencia Pública General de GNU (GPL), Versión 3.0"
    license-link: "http://www.gnu.org/licenses/gpl-3.0.html"
    license-contents-notice: "su documentación bajo "
    license-contents-version: "CC BY-SA 3.0"
    license-contents-link: "http://creativecommons.org/licenses/by-sa/3.0/es/"
    back-to-blog: "Volver atrás"
    doc-samples: Proyectos demo
    doc-guides: Guías de inicio
    doc-tutorials: Tutoriales
    doc-reference: Referencia
    doc: Documentación
    additional-doc: Documentación adicional
    source-code: Código fuente
    less-1: Leído hace menos de 1 minuto
    1-minute: Leído hace un minuto
    read: minutos hace que fue leído
    see-more: Leer más...
    changelog: Control de cambios
    modified: última modificación en


##{{ site.t[page.lang].grid-title }}

# Change the directory where Jekyll will read files
#source:

# Change the directory where Jekyll will write files
#destination:


